export const ROUTES = {
  HOME: "/",
  MAP: "/map",
  LIBRARY: "/library",
  YOUR_LIBRARY: "/library/your",
  NOTIFICATIONS: "/notifications",
  STORY: "/story/:id",
  DAILY_CHALLENGE: "/daily-challenge",
  PROFILE: "/profile",
  EDIT_PROFILE: "/profile/edit",
  DELETE_ACCOUNT: "/profile/delete",
  CHANGE_PASSWORD: "/profile/password",
  CHANGE_EMAIL: "/profile/email",
  PAYMENT_METHODS: "/profile/payments",
  ACTIVITY: "/profile/activity",
  REPORT_ISSUE: "/profile/report",
  SIGN_IN: "/signin",
  SIGN_UP: "/signup",
  ERROR_404: "*",
};